### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by ochrons** [tpolecat/skunk#102]
A list of issues in documentation that a new user easily runs into:

- [ ] Use of `gimap` is only documented in the twiddle list reference, although it's a huge boilerplate saver. Should be used in general examples with case classes
- [ ] A list of all supported types and associated codecs (like `varchar` and `int4`) is missing

... more to come :)

**Comment by tpolecat** [comment]
Thanks!

**Comment by tpolecat** [comment]
I improved the doc here, and the list of types and codecs is in the reference material so I think at least these two points are resolved. And since you moved on to doobie I'm going to go ahead and close this. ;-)
