### ISSUE TITLE
Incorrect completion for UPDATE

### ISSUE THREAD

**Issue by DylanArnold** [tpolecat/skunk#128]
`case Patterns.Update(s) => apply(Completion.Delete(s.toInt))` should be an `Update` completion in `CommandComplete`.

Happy to PR this if you want but I thought it probably should have a test and I wasn't sure on the best way to write it.

**Comment by tpolecat** [comment]
Doh! That seems wrong 😉 

You can modify this test to insert, update, then delete. Ideally it would have its own case but that's fine for now.

https://github.com/tpolecat/skunk/blob/master/modules/tests/src/test/scala/CommandTest.scala#L70

Thanks!
