### ISSUE TITLE
Codecs for nested and fixed-length arrays.

### ISSUE THREAD

**Issue by kalexmills** [tpolecat/skunk#168]
I'm thinking about how to build `Codec`s for arbitrary [PostgreSQL array types](https://www.postgresql.org/docs/9.0/arrays.html), including arbitrary-depth nested arrays and fixed-length arrays (mapped using homogeneously typed Scala tuples). 

A general solution might be able to use a signature like this.

`def array[A](scalarCodec: Codec[A]): Codec[List[A]]`

But `Codec[A]` is Semigroupal, and exposes `types: List[type]`. For this use-case, we only want to admit instances of `Codec[A]` which map to scalars and have not been built using the twiddle syntax.

Does including that kind of support in the base library make sense, or clutter the API?

**Comment by tpolecat** [comment]
It's ok to select arrays of record types (the schema type is `_record`). These will need to be decoded using the underlying composed elements. We need to get this figured out before dealing with arrays.

What I would like to see I think is a nat-indexed type like `Arr[3, A]` which acts like an indexed sequence of `Arr[2, A]` and so on, where `Arr[1, A]`'s elements are `A`s. And just say you have to use 2.13 or shapeless `Witness` to get access to those types.

**Comment by kalexmills** [comment]
So `Arr[3, Long]` could map to column types `int8[][][]`, and would be handled internally by deferring to `Arr[2, Long]`.

Would the `Arr[3, Long]` type be exposed in the public API, or would we use some typelevel recursion to convert it to a `Array[Array[Array[long]]]` (or whatever `Seq` type makes most sense) before returning it?

**Comment by tpolecat** [comment]
I don't really know what makes sense. Postgres arrays have to be rectangular but Scala arrays don't have to be, and I don't have a good solution for that.

**Comment by kalexmills** [comment]
Ok, so I'm looking into it further and there's other ways in which postgres arrays are weird.

Nesting levels and length specifiers for array types are erased at runtime, which means :any: array type can be arbitrarily nested [[1]](https://www.postgresql.org/docs/12/arrays.html#ARRAYS-DECLARATION) and have different lengths.

Which means that the below is valid in postgres (tested on postgres 12).
```
create table test (a integer[]);
insert into test (a) values ('{{1,2},{2,1}}');
insert into test (a) values ('{{1,2},{{1},{2}}}');
insert into test (a) values ('{{1,2},{{1,2},{2,2}}}');
insert into test (a) values ('{1}');
```
yields a table with these values:
```
postgres=# select * from test;
                  a
-------------------------------------
 {{1,2},{2,1}}
 {{{1},{2}},{{1},{2}}}
 {{{1,2},{NULL,NULL}},{{1,2},{2,2}}}
 {1}
```
You can get back a slightly different shape than the one you wrote out. It looks like postgres is forcing things to become rectangular when they are not (especially in the `{{1,2},{{1},{2}}} =  {{{1},{2}},{{1},{2}}}` case).

Insertion and retrieval of postgres arrays are not perfect inverses which is... annoying. Anyway, It seems like the only way to be able to read what we write is to provide more type-checking in the API than postgres does.

That might not fit all use-cases, though.

**Comment by tpolecat** [comment]
String parsing is more lenient than the `ARRAY` constructor. I want `ARRAY` semantics so round-tripping is predictable.

```sql
rnorris=# select array[array[1,2], array[3,4]];
     array     
---------------
 {{1,2},{3,4}}
(1 row)

rnorris=# select array[array[1,2], array[3]];
ERROR:  multidimensional arrays must have array expressions with matching dimensions
rnorris=# 
```

**Comment by kalexmills** [comment]
That particular is checked for with strings too...
```
postgres=# insert into test (a) values ('{{1,2},{{1}}}');
ERROR:  malformed array literal: "{{1,2},{{1}}}"
LINE 1: insert into test (a) values ('{{1,2},{{1}}}');
                                     ^
DETAIL:  Multidimensional arrays must have sub-arrays with matching dimensions.
```
...but the nesting issue I raised goes away, so that's good.

**Comment by kalexmills** [comment]
> It's ok to select arrays of record types (the schema type is `_record`). These will need to be decoded using the underlying composed elements. We need to get this figured out before dealing with arrays.

You mean in order to support composite records like in the example query here?
`create table test2 (a int, b int)`
` select Array[tuple, tuple2] from test2 tuple inner join test2 tuple2 on true;`
```
---------------------
 {"(2,3)","(2,3)"}
 {"(2,3)","(26,5)"}
 {"(2,3)","(2,)"}
 {"(2,3)","(,2)"}
 {"(2,3)","(,)"}
 {"(26,5)","(2,3)"}
...
```
