### ISSUE TITLE
Better reporting of error with enumerated data type in database

### ISSUE THREAD

**Issue by debasishg** [tpolecat/skunk#198]
Here's the issue:

* I have an enumerated data type in Postgres

```
banking=> \dT+ accounttype
                                         List of data types
 Schema |    Name     | Internal name | Size | Elements |  Owner   | Access privileges | Description 
--------+-------------+---------------+------+----------+----------+-------------------+-------------
 public | accounttype | accounttype   | 4    | Checking+| postgres |                   | 
        |             |               |      | Savings  |          |                   |
```

* Here's the codec that I defined in Scala ..
```
val accountType = enum(AccountType, Type("accountType"))
```

* Here's a sample decoder that uses it ..
```
val decoder: Decoder[Account] =
    (varchar ~ varchar ~ accountType ~ numeric ~ timestamp ~ timestamp.opt ~ numeric).map {
      case no ~ nm ~ tp ~ ri ~ dp ~ dc ~ bl =>
        tp match {
          case Checking =>
            CheckingAccount(AccountNo(no), AccountName(nm), Option(dp), dc, Balance(USD(bl)))
          case Savings =>
            SavingsAccount(AccountNo(no), AccountName(nm), ri, Option(dp), dc, Balance(USD(bl)))
        }
    }
```

* and here's the query ..
```
val selectByAccountNo: Query[AccountNo, Account] =
    sql"""
        SELECT a.no, a.name, a.type, a.rateOfInterest, a.dateOfOpen, a.dateOfClose, a.balance
        FROM accounts AS a
        WHERE a.no = ${varchar.cimap[AccountNo]}
       """.query(decoder)
```

* The 3rd column a.type is the enum typed column. When I execute this query, I get an `UnknownOidException` for the enum ..
```
The actual and asserted output columns are
[error] 🔥  
[error] 🔥    no              varchar    ->  varchar                         
[error] 🔥    name            varchar    ->  varchar                         
[error] 🔥    type            16434      ->  accountType  ── unknown type oid
[error] 🔥    rateofinterest  numeric    ->  numeric                         
[error] 🔥    dateofopen      timestamp  ->  timestamp                       
[error] 🔥    dateofclose     timestamp  ->  timestamp                       
[error] 🔥    balance         numeric    ->  numeric
```
@tpolecat suggested on gitter the following ..

> Pass strategy = Typer.Strategy.SearchPath as another named argument when you specify all your session properties.
> This is an optimization … if you're using built-in types only then it doesn't have to consult the system tables to get type metadata.

However it would be good to have this suggestion included as part of the error message.

**Comment by tpolecat** [comment]
There are a pair of related exceptions, both poorly named. 

- `UnknownTypeException` for parameters, where we know the `Type` but not the oid.
- `UnknownOidException` for row descriptions, where we know the oid but not the `Type`.

The `Typer` maps between these, and when it's unable to do so you get one error or the other. In any case this wording is better for the first error. Still need to do the second.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/1200131/85192296-99ddcb00-b287-11ea-98b5-df0a96a1a658.png">
