### ISSUE TITLE
Commands not completing until next query/command is run

### ISSUE THREAD

**Issue by dpnova** [tpolecat/skunk#210]
Here's a gist: https://gist.github.com/dpnova/06e3650b943d1f80321bbba8364e4f92

Basically I think a sync needs to be sent here: https://github.com/tpolecat/skunk/blob/813025335411dd09584010f50ae02e7e37808902/modules/core/src/main/scala/net/protocol/Execute.scala#L33

This is the relevant section from the postgres docs.

```
  At completion of each series of extended-query messages, the frontend should issue a Sync message. This parameterless 
  message causes the backend to close the current transaction if it's not inside a BEGIN/COMMIT transaction block ("close" 
  meaning to commit if no error, or roll back if error). Then a ReadyForQuery response is issued. The purpose of Sync is to 
  provide a resynchronization point for error recovery. When an error is detected while processing any extended-query message, 
  the backend issues ErrorResponse, then reads and discards messages until a Sync is reached, then issues ReadyForQuery 
  and returns to normal message processing. (But note that no skipping occurs if an error is detected while processing Sync — 
  this ensures that there is one and only one ReadyForQuery sent for each Sync.)
```

Sorry I'm being rushed out the door for kids birthdays, but I can do any further testing etc here, or even the fix if we think the Sync is the answer. I'll be back a little bit later.

**Comment by dpnova** [comment]
I forgot to mention, when this is running you can check the locks in postgres to see the insert hasn't completed.

**Comment by tpolecat** [comment]
Thanks, I think your suggestion was exactly right.

**Comment by tpolecat** [comment]
I tagged v0.0.13, should be available in a bit. Let me know if it works.

**Comment by dpnova** [comment]
Just did some quick testing and things look good thus far!

I think the only case you may not want to sync immediately is if there's more commands to send, but I'm not sure that is actually ever a requirement.
