### ISSUE TITLE
Implement SCRAM-SHA-256 authentication scheme

### ISSUE THREAD

**Issue by sbuzzard** [tpolecat/skunk#255]
Our corporate database servers, it turns out, are requiring this.  I'll take a crack at doing it in the next couple weeks if no one else has plans to.

**Comment by tpolecat** [comment]
This doesn't look too bad. I recommend you add another server (on another port) to the docker-compose file and configure it to use SASL. You will need to implement the SASL message types (they didn't exist in the protocol version I implemented) and then add a handler [here](https://github.com/tpolecat/skunk/blob/master/modules/core/src/main/scala/net/protocol/Startup.scala) ... see the MD5 code.

**Comment by tpolecat** [comment]
Also please update the [doc](https://github.com/tpolecat/skunk/blob/master/modules/docs/src/main/paradox/reference/Sessions.md) … it will be nice to add another authentication to the currently very short list!

**Comment by mpilquist** [comment]
Draft PR here: https://github.com/tpolecat/skunk/pull/257

Need to update docs and probably make a cleanup pass through the code. Comments welcome though, in particular the need for an additional dependency (Java, not Scala).
