### ISSUE TITLE
timestamptz codec with UTC

### ISSUE THREAD

**Issue by tolikbotov** [tpolecat/skunk#313]
I need to save java.time.Instant object to Postgres 10 db. Server zone is Moskow.

I have a table: 

```
CREATE TABLE public.table1
(
    id integer NOT NULL DEFAULT nextval('manufacture_bindings_id'::regclass),
    manufacture_id integer NOT NULL,
    channel_id character varying COLLATE pg_catalog."default" NOT NULL,
    last_sync_time timestamp with time zone,
    CONSTRAINT "ManufactureBindings_pkey" PRIMARY KEY (manufacture_id)
)
```

I created a Codec:

`val instantCodec: Codec[Instant] = timestamptz.imap(_.toInstant)(_.atOffset(ZoneOffset.UTC))`

After all I do:

```
case class CaseClass1(id: Int, manufactureId: Int, channelId: String, lastSyncTime: Option[Instant])

val instant = Instant.parse("2020-11-23T10:24:31.000Z")

val cs1 = CaseClass1(1, 1, "2", Some(instant))

val command: Command[CaseClass1] = 
      sql"""
        UPDATE public.table1
        SET    last_sync_time = ${instantCodec.opt}
        WHERE  id = $int4
      """.command
        .contramap { case CaseClass1(id, _, _, lastSyncTime) => lastSyncTime ~ id }
```

I expect to see in table1: _"2020-11-23 13:24:31+03"_, but i see _"2020-11-23 10:24:31+03"_  . 

This looks like a bug.

If I change codec like this:

`val instantCodec: Codec[Instant] = timestamptz.imap(_.toInstant)(_.atOffset(ZoneOffset.of("+1")))`

Value in table1 is  _"2020-11-23 13:24:31+03"_ .

**Comment by tpolecat** [comment]
Good catch, thank you!

**Comment by tpolecat** [comment]
Can you try `0.0.22-M1+26-255d8cd6-SNAPSHOT` (you will need to add the sonatype snapshot resolver) and confirm that the fix works? If so I will tag M2. Thanks!

**Comment by tolikbotov** [comment]
_0.0.22-M1+26-255d8cd6-SNAPSHOT_ works as expected. Thank you.
