### ISSUE TITLE
Skunk's raison d'etre

### ISSUE THREAD

**Issue by costa100** [tpolecat/skunk#37]
This is not an issue, just a question, what is the purpose of skunk given that we have doobie? What's the difference? Why would one use skunk (with a postgresql backend) and not doobie?

Thank you

**Comment by Igosuki** [comment]
Clearly, doobie is a JDBC wrapper, while Skunk uses postgre's protocols. I for one am very excited !

**Comment by tpolecat** [comment]
I give a lot of reasons in my Scala Days talk. I'll add a link to it here when the video is available.

**Comment by costa100** [comment]
@tpolecat - thanks

**Comment by dimitarg** [comment]
https://portal.klewel.com/watch/webcast/scala-days-2019/talk/28/

I highly recommend watching the whole thing, it gives raison d'etre, peak at internals, example use as well as general thoughts on program design

**Comment by Igosuki** [comment]
I'm willing to experiment this lib in an API already using Doobie (~100k LoC)

**Comment by nafg** [comment]
Differences are also discussed by Rob on this Scala Logs episode: https://open.spotify.com/episode/5yX2y0rspokvELFvEvfeZZ
