### ISSUE TITLE
Fix temporal codecs (and test them)

### ISSUE THREAD

**Issue by asoltysik** [tpolecat/skunk#42]
Temporal codecs currently do not work too well.

For example:
https://github.com/tpolecat/skunk/blob/346d42bcb3479c7ed9e59ae77e59c79c92d7d1ad/modules/core/src/main/scala/codec/TemporalCodecs.scala#L23
This uses format method on String instead of DateTimeFormatter.

https://github.com/tpolecat/skunk/blob/346d42bcb3479c7ed9e59ae77e59c79c92d7d1ad/modules/core/src/main/scala/codec/TemporalCodecs.scala#L33
I think this isn't quite right, it wouldn't decode e.g. `02:03:06.33` or `02:03:06` and these values are of type `time(6)`. `DateTimeFormatterBuilder` offers quite a nice way to build these, I'm thinking something along these lines:
```scala
private def timeFormatter(precision: Int): DateTimeFormatter = {
    val requiredPart = new DateTimeFormatterBuilder()
      .appendValue(HOUR_OF_DAY, 2)
      .appendLiteral(':')
      .appendValue(MINUTE_OF_HOUR, 2)
      .appendLiteral(':')
      .appendValue(SECOND_OF_MINUTE, 2)

    if(precision > 0) {
      requiredPart.optionalStart()
        .appendFraction(MILLI_OF_SECOND, 0, precision, true)
        .optionalEnd()
        .toFormatter()
    } else {
      requiredPart.toFormatter()  
    }  
  }
```

If I get a green light on this I would love to provide a PR this week.

**Comment by tpolecat** [comment]
Ah yeah, the first one is a bug for sure. I haven't tested these so yeah if you can come up with a better way to do it, with tests, that would be great. :+1:

**Comment by asoltysik** [comment]
@tpolecat Some thoughts on the open PR: 
1. In the PR I made timestamptz convert to `java.time.OffsetDateTime`. I believe the best type for timestamptz is in fact `java.time.Instant`. First of all, timestamptz doesn't actually hold the time zone/offset information so it really doesn't make sense to parse it as OffsetDateTime - the time zone there will always be the same when reading. That's also what [Haskell's opaleye does](http://hackage.haskell.org/package/opaleye-0.6.7004.0/docs/Opaleye-PGTypes.html#t:PGTimestamptz), i.e. it maps timestamptz to UTCTime, which is haskell's equivalent of Instant.
2. `timetz` doesn't make much sense. Quoting from postgres manual:
    > The type time with time zone is defined by the SQL standard, but the definition exhibits properties which lead to questionable usefulness. In most cases, a combination of date, time, timestamp without time zone, and timestamp with time zone should provide a complete range of date/time functionality required by any application.

    Interestingly, opaleye doesn't expose timetz. I am not sure whether that's the right choice. Arguably, it's much easier to write your own codecs in skunk than in opaleye, but having it by default would still save some time for some people.

**Comment by tpolecat** [comment]
With `OffsetDateTime` the offset is applied on write and is zero on read, which aligns with the behavior of `timestamptz`. That's my intent here.

I have no strong feelings about `timetz`'s usefulness but if there's a compatible JDK type I would like to support it.
