### ISSUE TITLE
Provide short comparison with alternatives

### ISSUE THREAD

**Issue by david-bouyssie** [tpolecat/skunk#45]
Could you please provide a short comparison between your library and existing alternatives such as:
- https://github.com/alaisi/postgres-async-driver
- https://github.com/cretz/pgnio
- https://github.com/benfante/libpq-wrapper

And I'm also interested in knowing if you provide an API for CopyTo/CopyFrom.

**Comment by tpolecat** [comment]
I don't have the time or interest to evaluate Java libraries, but if you're like to do so and want make a PR with your findings I would be happy to add them to the documentation.

I do plan to support the `COPY` API.
