### ISSUE TITLE
Option to set TCP_NODELAY

### ISSUE THREAD

**Issue by vquintin** [tpolecat/skunk#450]
Recently, I have noticed my query preparations and executions take ~50ms but I could not tell why.
Today, I got the luck to find [this](https://mysteries.wizardzines.com/50ms-request.html).
I checked and this is the issue I have with skunk and postgres.

To lower my query latencies, I would like to set `TCP_NODELAY` in skunk. The option is supported in fs2 `Socket` and it should only be a matter of making it available in `Session.pooled`.

**Comment by vquintin** [comment]
The fs2 socket options changed between CE2 version of fs2 and the CE3 version of fs2.
For better API stability, we may need to migrate skunk to cats effect 3 before making the socket options available in the `Session` API.

**Comment by tpolecat** [comment]
Thanks, I will look into this. I haven't really spent any time optimizing yet.
