### ISSUE TITLE
Unknown completion 'CREATE VIEW'

### ISSUE THREAD

**Issue by dfrese** [tpolecat/skunk#527]
Got this in version 0.0.28

🔥  SkunkException
🔥
🔥    Problem: Just constructed an unknown completion 'CREATE VIEW'.  Note that your
🔥             program has not crashed. This message is here to annoy you.
🔥       Hint: Please open an issue, or open a PR adding a case in Completion.scala
🔥             and a parser in CommandComplete.scala
🔥

**Comment by tpolecat** [comment]
Thanks!
