### ISSUE TITLE
ScalaJS release with cats-effect 2?

### ISSUE THREAD

**Issue by fdietze** [tpolecat/skunk#624]
Hi, I just wanted to try to use skunk in an scalajs project, running on AWS lambda.

The problem is, that my project is stuck on cats-effect 2, because of other libraries.

I noticed that there are cats-effect 2 versions, like `0.28` but these are not published for ScalaJS yet. Would it be possible to publish such an older version for ScalaJS, or is this version outdated and out of scope?

**Comment by tpolecat** [comment]
No, sorry, I'm not maintaining a CE2 branch. You may have better luck upgrading your other dependencies to CE3.

**Comment by fdietze** [comment]
I understand.

Because a transitive dependency is using Monix, which is having it's own problems migrating to CE3:
- https://github.com/monix/monix/issues/1502

As an intermediate solution, I'm thinking about forking the last Skunk version using CE2 and cross-compiling it to ScalaJS. Dou you think that's easy to do?

**Comment by tpolecat** [comment]
You can try but I think it will not be easy. You'll also have to downgrade fs2 and scodec. You should look at the PR that moved us to CE3 to see what was involved.
