### ISSUE TITLE
Regression in 0.3.0 when streaming results and paging

### ISSUE THREAD

**Issue by pjan** [tpolecat/skunk#628]
I'm not sure how to capture this issue well, so feel free to ask more questions.

What we're doing is getting a list of objects from a table, with a Limit on the number of elements we're taking (say 100). We're also passing a second argument to the skunk `stream` function, limiting the number of results returned per chunk (say 50).

When we do this, we get an postgres 34000 raised (or a `SqlState.InvalidCursorName`)

We can consistently reproduce this whenever we're requesting more elements than the chunk size we provide in that function call.

Solution right now for us is rolling back to `0.2.2` given the consistency we get reproducing this, this might merit a patch fix in the `0.3.0` series.

**Comment by tomp4l** [comment]
We seem to be hitting the same issue I think, getting error messages like `Portal "portal_10" does not exist.` with error code 34000.

**Comment by tpolecat** [comment]
Yep, working on this today.
