### ISSUE TITLE
Documentation out of date 

### ISSUE THREAD

**Issue by yadavan88** [tpolecat/skunk#787]
I was trying out skunk and implemented a basic setup using microsite, using the version 0.3.2 as per the doc.
But when I try to use 0.5.x now, it has breaking changes for _use()_ on _prepare()_. 
I am now trying to find out how to fix these issues. 

It would be awesome if the microsite can be updated

**Comment by mpilquist** [comment]
Thanks, just updated the site. See https://github.com/tpolecat/skunk/releases/tag/v0.4.0 for tips on upgrading. The short version is change `.prepare(...)` to `.prepareR(...)`.

**Comment by yadavan88** [comment]
Thank you so much for quick response :)
